ARG base_image
FROM ${base_image}

# Install packages that we want to make available at build time
RUN zypper -n in curl wget git tar gzip liblzma5 xz zip; zypper clean

COPY ./target/release/metabuildpack /usr/local/bin/metabuildpack

# Set required CNB information
ARG stack_id
ENV CNB_STACK_ID=${stack_id}
LABEL io.buildpacks.stack.id=${stack_id}

# Set user and group (as declared in base image)
USER ${CNB_USER_ID}:${CNB_GROUP_ID}
