# Buildpacks to include in builder
[[buildpacks]]
uri = "docker://atgracey/testbuilder:latest"

# Order used for detection
[[order]]
[[order.group]]
id = "atgracey/testbp1"
version = "0.0.1"

# Stack that will be used by the builder
[stack]
id = "io.buildpacks.agracey.stacks.opensuse-15-3"
run-image = "docker.io/atgracey/testbprun:latest"
build-image = "docker.io/atgracey/testbprun:latest"